package.path='config/hammerspoon/?.lua;'..package.path
local names={'AlfredExcluded','MacPass'}
local saved,reads=nil,0
hs={plist={read=function(path)
  reads=reads+1
  if path:find('Alfred%-Preferences.plist') then return {syncfolder='~/SyncedPrefs'} end
  if path:find('/SyncedPrefs/') then return {blacklist=names} end
  error('Missing file')
end},settings={get=function(key)
  if key=='hyper.clipboardAlfredBlacklist' then return saved end
  return {'custom.secret.app'}
end,set=function(_,value)saved=value;return true end},
timer={doEvery=function()error('Blacklist must not poll')end}}
local policy=require('private/modules/hyper-clipboard-policy').new()
local function app(name,bundle)return {name=function()return name end,bundleID=function()return bundle end}end
assert(policy.source:find('/SyncedPrefs/'))
assert(policy:blocked(app('AlfredExcluded','test'),{}))
assert(policy:blocked(app('MacPass','test'),{}))
assert(policy:blocked(app('Bitwarden','test'),{}))
assert(policy:blocked(app('密码','com.apple.Passwords'),{}))
assert(policy:blocked(app('Private','custom.secret.app'),{}))
assert(policy:blocked(nil,{}))
for _,uti in ipairs({'org.nspasteboard.ConcealedType','org.nspasteboard.TransientType','org.nspasteboard.AutoGeneratedType','com.agilebits.onepassword'}) do
  assert(policy:blocked(app('Browser','browser'),{'public.utf8-plain-text',uti}))
end
assert(not policy:blocked(app('Browser','browser'),{'public.utf8-plain-text'}))
names={'NewExcluded'}
local before=reads
policy=require('private/modules/hyper-clipboard-policy').new()
assert(reads==before and policy:blocked(app('AlfredExcluded','test'),{}))
assert(policy:sync())
assert(policy:blocked(app('NewExcluded','test'),{}))
assert(not policy:blocked(app('AlfredExcluded','test'),{}))
assert(policy:blocked(app('MacPass','test'),{}))
hs.plist.read=function()error('Unavailable')end
assert(not policy:sync())
assert(policy:blocked(app('NewExcluded','test'),{}))
assert(saved.names[1]=='NewExcluded')
print('Clipboard policy: initial import, persistent snapshot, manual sync, failure retention and exclusions passed')
