#!/usr/bin/env bash
# A dmenu display config prompt

exists()
{
  command -v "$1" >/dev/null 2>&1
}

if [[ $# -ge 1 ]]; then
  chosen="$1"
else
  choices="primary\nsecondary\n\
extend-top\nextend-left\nextend-right\nextend-bottom\n\
manual-config"

  chosen=$(echo -e "$choices" | dmenu -i)
fi

case "$chosen" in
  primary) mons -o ;;
  secondary) mons -s ;;
  extend-top) mons -e top ;;
  extend-left) mons -e left ;;
  extend-right) mons -e right ;;
  extend-bottom) mons -e bottom ;;
  manual-config) arandr ;;
  *) chosen='' ;;
esac

# Reset i3 and wallpaper if there was a selection
if [[ -n $chosen ]]; then
  exists wallpaper && wallpaper
  exists i3-msg && i3-msg restart
fi
