#!/usr/bin/env bash
# A dmenu display config prompt

script_path=$(dirname "$(realpath "${BASH_SOURCE[0]}")")
source "$script_path/helper.sh"

if [ $# -ge 1 ]; then
  chosen="$1"
else
  choices="primary\\nsecondary\\nextend-top\\nextend-left\\nextend-right\\nextend-bottom\\nmanual-config"
  chosen=$(dmenu_filter "$choices" 'Choose display')
fi

case "$chosen" in
  primary) mons -o ;;
  secondary) mons -s ;;
  extend-top) mons -e top ;;
  extend-left) mons -e left ;;
  extend-right) mons -e right ;;
  extend-bottom) mons -e bottom ;;
  manual-config) arandr ;;
  *) chosen='' ;;
esac

# Reset i3 and wallpaper if there was a selection
if [ -n "$chosen" ]; then
  exists wallpaper && wallpaper
  exists polybar-launch && polybar-launch
fi
