#!/usr/bin/env bash
# Should be run with sudo.
# Gives a dmenu prompt to mount unmounted drives.
# If they're in /etc/fstab, they'll be mounted automatically.
# Otherwise, you'll be prompted to give a mountpoint from already existsing directories.
# If you input a novel directory, it will prompt you to create that directory.

script_path=$(dirname "$(realpath "${BASH_SOURCE[0]}")")
source "$script_path/helper.sh"

mountable=$(lsblk -lp | grep part | grep -v "t /" | awk '{print $1, "(" $4 ")"}')
[[ "$mountable" = "" ]] && exit 1
chosen=$(dmenu_filter "$mountable" 'Mount drive' | awk '{print $1}')
[[ "$chosen" = "" ]] && exit 1
mount "$chosen" && exit 0
# You may want to change the line below for more suggestions for mounting.
# I.e. you can increase the depth of the search, or add directories.
# This will increase the load time briefly though.
dirs=$(find /mnt /media /mount /home -type d -maxdepth 5 2>/dev/null)
mountpoint=$(dmenu_filter "$dirs" "Mount point")
[[ "$mountpoint" = "" ]] && exit 1
if [[ ! -d "$mountpoint" ]]; then
  mkdiryn=$(dmenu_filter "No\nYes" "Create non-exist mount point $mountpoint?")
  [[ "$mkdiryn" = Yes ]] && sudo mkdir -p "$mountpoint"
fi
sudo mount "$chosen" "$mountpoint"
