#!/usr/bin/env bash
# A dmenu power config prompt

script_path=$(dirname "$(realpath "${BASH_SOURCE[0]}")")
source "$script_path/helper.sh"

if [[ $# -ge 1 ]]; then
  chosen="$1"
else
  choices="reload\nrestart\nexit"
  chosen=$(dmenu_filter "$choices" 'i3 controls')
fi

i3-msg "$chosen"
