#!/usr/bin/env bash
# Feed this script a link and it will give dmenu
# some choice programs to use to open it.

script_path=$(dirname "$(realpath "${BASH_SOURCE[0]}")")
source "$script_path/helper.sh"

# The URL will be shown visually in 30 characters or less
if [[ "${#1}" -gt 30 ]]; then
  visual="${1:0:20}"..."${1: -7}"
else
  visual="$1"
fi

choices="chromium\\nfeh\\nfirefox\\nmpv (float)\\nmpv (loop)\\nmpv\\nw3m\\nwget"
chosen=$(dmenu_filter "$choices" "Open '$visual' with")
case "$chosen" in
  chromium) chromium "$1" ;;
  feh) feh "$1" ;;
  firefox) firefox "$1" ;;
  mpv) mpv -quiet "$1" ;;
  "mpv (float)") mpv --geometry=+0-0 --autofit=30% --title="mpvfloat" /dev/video0 "$1" ;;
  "mpv (loop)") mpv -quiet --loop "$1" ;;
  w3m) w3m "$1" ;;
  wget) wget "$1" ;;
esac
