#!/usr/bin/env bash
# A dmenu power config prompt

script_path=$(dirname "$(realpath "${BASH_SOURCE[0]}")")
source "$script_path/helper.sh"

if [[ $# -ge 1 ]]; then
  chosen="$1"
else
  choices="sleep\nhibernate\npoweroff\nreboot"
  chosen=$(dmenu_filter "$choices" 'Power options')
fi

case "$chosen" in
  sleep) ~/.config/i3/scripts/lock suspend ;;
  hibernate) ~/.config/i3/scripts/lock hibernate ;;
  poweroff) systemctl poweroff ;;
  reboot) systemctl reboot ;;
esac
