#!/usr/bin/env bash
# A dmenu prompt to unmount drives.
# Provides you with mounted partitions, select one to unmount.
# Drives mounted at /, /boot and /home will not be options to unmount.
# This can be changed by modifying $exclusionregex.

script_path=$(dirname "$(realpath "${BASH_SOURCE[0]}")")
source "$script_path/helper.sh"

exclusionregex="\(/boot\|/home\|/\)$"
drives=$(lsblk -lp | grep "t /" | grep -v "$exclusionregex" | awk '{print $1, "(" $4 ")", "on", $7}')
[[ "$drives" = "" ]] && exit 1
chosen=$(dmenu_filter "$drives" 'Unmount drive' | awk '{print $1}')
[[ "$chosen" = "" ]] && exit 1
sudo umount $chosen
