#!/usr/bin/env bash
# Feed this script a link and it will give dmenu
# some choice programs to use to open it.

# The URL will be shown visually in 30 characters or less
if [[ "${#1}" -gt 30 ]]; then
  visual="${1:0:20}"..."${1: -7}"
else
  visual="$1"
fi

choices="mpv\nmpv (loop)\nwget\nfeh\nbrowser\nw3m\nmpv (float)"
chosen=$(echo -e "${choices}" | dmenu -i -p "How should I open '$visual'?")
case "$chosen" in
  mpv) mpv -quiet "$1" ;;
  "mpv (loop)") mpv -quiet --loop "$1" ;;
  wget) wget "$1" ;;
  browser) $BROWSER "$1" ;;
  feh) feh "$1" ;;
  w3m) w3m "$1" ;;
  "mpv (float)") mpv --geometry=+0-0 --autofit=30% --title="mpvfloat" /dev/video0 "$1" ;;
esac
