#!/usr/bin/env bash
# A dmenu recording prompt

script_path=$(dirname "$(realpath "${BASH_SOURCE[0]}")")
source "$script_path/helper.sh"

choices="screencast\nvideo\naudio"
chosen=$(dmenu_filter "$choices" 'Select recording style')
case "$chosen" in
  screencast) record-screencast ;;
  audio) record-audio ;;
  video) record-video ;;
esac
