#!/usr/bin/env bash

if [ $# = 0 ]; then
  echo 'Remount a path to remove noexec constraint.'
  echo 'Usage:'
  echo 'enable-exec [path]'
  echo 'Example:'
  echo 'enable-exec /tmp'
  echo 'enable-exec ~'
  exit 1
fi

if [ -d "$1" ]; then
  echo "Enter password to remount '$1' with exec option."
  sudo mount -o remount,exec "$1"
else
  echo "Path '$1' not exist."
fi
