#!/usr/bin/env bash

print_usage()
{
  cat << 'EOB' >&2
enable-exec: Remount a path to remove noexec constraint

[Synopsis]

enable-exec [path]

[Examples]

enable-exec /tmp
enable-exec ~
EOB
  exit 0
}

if [ $# = 0 ]; then
  print_usage
fi

if [ -d "$1" ]; then
  echo "Enter password to remount '$1' with exec option."
  sudo mount -o remount,exec "$1"
else
  echo "Path '$1' not exist."
fi
