#!/usr/bin/env bash

set -e

script_path=$(dirname "$(realpath "${BASH_SOURCE[0]}")")
source "$script_path/helper.sh"

exists winetricks || ( \
  echo 'This patch requires winetricks. Please install and retry.'; \
  exit 1 \
)

wineprefix="$HOME/.deepinwine/Deepin-WeChat"
eval "WINEPREFIX=\"${wineprefix}\" winetricks wenquanyi fakechinese"
