#!/usr/bin/env bash

set -e

script_path=$(dirname "$(realpath "${BASH_SOURCE[0]}")")
source "$script_path/helper.sh"

exists winetricks || ( \
  echo 'This patch requires winetricks. Please install and retry.'; \
  exit 1 \
)

shortcutPath='/usr/share/applications/deepin.com.wechat.desktop'
execPath=$(ag '^Exec=' "$shortcutPath" | awk -F\" '{print $2}')
wineprefix=$(ag '^WINEPREFIX=' $execPath | awk -F\" '{print $2}')
eval "WINEPREFIX=\"${wineprefix}\" winetricks wenquanyi fakechinese"
