#!/bin/sh

dotfiles_dir="${DOTFILES_HOME:-${XDG_CONFIG_HOME:-$HOME/.config}/dotfiles}"
[ -d "$dotfiles_dir" ] || dotfiles_dir="$HOME/.dotfiles"
. "$dotfiles_dir/config/sh/ssh-agent-connect.sh"
spawnPerUserSSHAgent
