#!/usr/bin/env bash
# Usage:
#   wallpaper <path-to-an-image> : set wallpaper with image
#   wallpaper                    : reload wallpaper

script_path=$(dirname `which $0`)
source "$script_path/helper.sh"

WALL="$HOME/.wallpaper"
[[ -f $1 ]] && ln -sf "$1" "$WALL"
exists feh && feh --bg-scale "$WALL"
exists betterlockscreen && betterlockscreen --update "$WALL" &>/dev/null &
