#!/usr/bin/env bash

print_usage()
{
  cat << 'EOB' >&2
window-move - move active window around in X

[Synopsis]

window-move [option]

[Options]

move_to_prev_display
move_to_next_display
move_to_display
show_prev_display
show_next_display
show_display
EOB
  exit 0
}

get_workspace_info()
{
  aw=$(xdotool getactivewindow)
  dt=$(xdotool get_num_desktops)
  dc=$(xdotool get_desktop)
}

move_to_display()
{
  local idx="$1"
  xdotool set_desktop_for_window $aw $idx
  xdotool set_desktop $idx
  xdotool windowactivate $aw
}

move_to_prev_display()
{
  move_to_display $(( (dc + dt - 1) % dt ))
}

move_to_next_display()
{
  move_to_display $(( (dc + 1) % dt ))
}

show_display()
{
  local idx="$1"
  xdotool set_desktop $idx
}

show_prev_display()
{
  show_display $(( (dc + dt - 1) % dt ))
}

show_next_display()
{
  show_display $(( (dc + 1) % dt ))
}

main()
{
  if [ $# = 0 ]; then
    print_usage
  fi

  get_workspace_info

  case $1 in
    move_to_prev_display)
      move_to_prev_display
      ;;
    move_to_next_display)
      move_to_next_display
      ;;
    move_to_display)
      move_to_display $2
      ;;
    show_prev_display)
      show_prev_display
      ;;
    show_next_display)
      show_next_display
      ;;
    show_display)
      show_display $2
      ;;
    *)
      print_usage
      ;;
  esac
}

main "$@"
