#!/usr/bin/env bash

# Pause music (mpd):
mpc pause

# Lock it up!
betterlockscreen --lock dimblur

# If still locked after 20 seconds, turn off screen.
sleep 20 && pgrep i3lock && xset dpms force off
