source "$partial_dir/env.sh"
source "$partial_dir/linux.sh"

config_pacman()
{
  timedatectl set-ntp true
  sudo pacman-mirrors -c Hong_Kong,Taiwan
}

pacman_install_pkgs()
{
  sudo pacman -Sy --needed --noconfirm `join ' ' "${pkgs[@]}"`
  unset pkgs
}

aur_install_pkgs()
{
  pkgs=( "${pkgs[@]/#/aur/}" )
  yay -Sy --needed `join ' ' "${pkgs[@]}"`
  unset pkgs
}

prepare_arch_env()
{
  config_pacman

  case $1 in
    'core')
      prepare_arch_env_core
      ;;
    'cli')
      prepare_arch_env_cli
      ;;
    'gui')
      prepare_arch_env_gui
      ;;
    'game')
      setup_arch_gaming
      ;;
    'all')
      prepare_arch_env_cli
      prepare_arch_env_gui
      ;;
    *)
      prepare_arch_env_core
      ;;
  esac
}

prepare_arch_env_core()
{
  prepare_arch_env_cli_core
  prepare_arch_env_gui_core
  brew_cleanup
}

prepare_arch_env_cli()
{
  prepare_arch_env_cli_core
  prepare_arch_env_cli_extra
  brew_cleanup
}

prepare_arch_env_gui()
{
  prepare_arch_env_gui_core
  prepare_arch_env_gui_extra
}

prepare_arch_env_cli_core()
{
  pkgs=(
    diff-so-fancy
    fd
    fx
    fzf
    git
    htop
    httpie
    jq
    less
    lsd
    openssh
    pamac-cli
    peco
    prettyping
    privoxy
    procs
    ripgrep
    rsync
    tealdeer
    the_silver_searcher
    tig
    tmux
    trash-cli
    unarchiver
    vim
    wget
    yay
    yazi
    zoxide
    zsh
  )
  pacman_install_pkgs

  # Set some configs for yay
  yay --save --nocleanmenu --nodiffmenu --noupgrademenu --noremovemake

  pkgs=(
    find-the-command
    lf-bin
    navi
    urlview
  )
  aur_install_pkgs

  install_linuxbrew
  install_nix_brew_runtimes

  basic_env_setup
  apply_linux_app_configs
  fix_ENOSPC
}

prepare_arch_env_cli_extra()
{
  pkgs=(
    android-tools
    aria2
    autossh
    axel
    bat
    broot
    calcurse
    checkbashisms
    cloc
    cmake
    cmatrix
    cmus
    cowsay
    cpanminus
    cpulimit
    dnsmasq
    docker
    docker-compose
    dog
    dstat
    duf
    ebtables
    ffmpeg
    ffmpegthumbnailer
    figlet
    fish
    flatpak
    fortune-mod
    fq
    frogmouth
    gdu
    gifsicle
    git-delta
    git-lfs
    github-cli
    gitui
    glances
    glow-bin
    go
    gping
    graphviz
    haproxy
    hashcat
    helix
    hexyl
    hub
    hyperfine
    iftop
    imagemagick
    iptables-nft
    irssi
    jdk-openjdk
    jless
    jpegoptim
    kubectl
    lazygit
    libvirt
    lolcat
    mc
    mediainfo
    micro
    minikube
    mpc
    mpd
    mps-youtube
    mpv
    multitail
    musikcube-bin
    mutt
    ncdu
    ncmpcpp
    neovim
    nghttp2
    ntfysh-bin
    nyancat
    offlineimap
    oha
    onefetch
    optipng
    p7zip
    pamixer
    pandoc-cli
    perl-image-exiftool
    pkgfile
    playerctl
    pngquant
    poppler
    progress
    proxychains-ng
    qemu
    ranger
    shellcheck
    sl
    snapd
    sniffnet
    starship
    toolong
    translate-shell
    transmission-cli
    tree
    unrar
    unzip
    v2ray
    v2ray-domain-list-community
    v2ray-geoip
    vagrant
    w3m
    websocat
    wtf
    xan
    you-get
    yt-dlp
    zip
  )
  pacman_install_pkgs

  # Set some configs for yay
  yay --save --nocleanmenu --nodiffmenu --noupgrademenu --noremovemake

  pkgs=(
    cheat-bin
    dive
    downgrader
    fpp
    fswatch
    git-bug-bin
    git-quick-stats
    gitflow-avh
    go-musicfox-bin
    google-cloud-cli
    icdiff
    lazydocker-bin
    lazynpm
    miniconda3
    mons
    mycli
    nb
    ocrmypdf
    pdfsandwich
    pgcli
    powershell-bin
    sc-im
    sparklines-git
    touchpad-state-git
    ttf-weather-icons
    ueberzugpp
    xdg-ninja
  )
  aur_install_pkgs

  extra_env_setup

  sudo systemctl enable --now snapd.socket # enable snapd
}

prepare_arch_env_gui_core()
{
  pkgs=(
    alacritty
    appmenu-gtk-module
    arandr
    autorandr
    blueman
    dmenu
    dunst
    fcitx
    fcitx-configtool
    fcitx-im
    fcitx-rime
    feh
    firefox
    flameshot
    foliate
    galculator
    gsimplecal
    i3-wm
    libdbusmenu-glib
    libdbusmenu-gtk2
    libdbusmenu-gtk3
    lxappearance
    lxsession
    lxtask
    maim
    network-manager-applet
    noto-fonts
    noto-fonts-cjk
    noto-fonts-emoji
    pa-applet
    parcellite
    picom
    polybar
    python-pywal
    redshift
    rofi
    rofi-scripts
    thunar
    thunar-archive-plugin
    thunar-media-tags-plugin
    thunar-shares-plugin
    thunar-volman
    ttf-font-awesome
    ttf-meslo-nerd
    ttf-sarasa-gothic
    ttf-sourcecodepro-nerd
    tumbler
    udiskie
    vala-panel-appmenu-xfce-git
    wqy-zenhei
    xautomation
    xbindkeys
    xcape
    xclip
    xorg-apps
    xscreensaver
    xsecurelock
    xsel
    xss-lock
    zathura
    zathura-cb
    zathura-djvu
    zathura-pdf-mupdf
    zathura-ps
  )
  pacman_install_pkgs

  pkgs=(
    betterlockscreen
    gluqlo-git
    i3ass
    jumpapp
    nerd-fonts-fira-code
    sublime-merge
    sublime-text-4
    visual-studio-code-bin
    xgetres
    xinit-xsession
  )
  aur_install_pkgs

  install_st
  set_default_apps
}

prepare_arch_env_gui_extra()
{
  pkgs=(
    android-file-transfer
    arc-gtk-theme
    arc-icon-theme
    chromium
    copyq
    drawing
    file-roller
    freerdp
    handbrake
    hardinfo
    kdiff3
    keepassxc
    kitty
    materia-gtk-theme
    neofetch
    pdfarranger
    qutebrowser
    remmina
    rxvt-unicode
    scrcpy
    sqlitebrowser
    telegram-desktop
    termite
    tilda
    virt-manager
    virtualbox
    winetricks
    wkhtmltopdf
    xcursor-simpleandsoft
    zeal
  )
  pacman_install_pkgs

  pkgs=(
    android-sdk
    android-sdk-platform-tools
    android-studio
    corplink-bin
    cursor-bin
    deepin-wine-tim
    deepin-wine-wechat
    dropbox
    feedreader
    feishu-bin
    genymotion
    git-cola
    google-chrome
    joplin
    kitematic
    losslesscut
    mailspring
    marktext-bin
    microsoft-edge-stable-bin
    musixmatch-bin
    qqmusic-bin
    rslsync
    screenkey
    slack-desktop
    spotify
    thorium-bin
    ttf-ms-fonts
    urxvt-fullscreen
    urxvt-resize-font-git
    v2raya-bin
    wechat-uos
    whatsapp-for-linux
  )
  aur_install_pkgs
}

setup_arch_gaming()
{
  pkgs=(
    desmume
    dosbox
    higan
    mame
    openra
    pcsx2
    ppsspp
    snes9x-gtk
    steam
    vbam-wx
  )
  pacman_install_pkgs

  pkgs=(
    dosbox-x
  )
  aur_install_pkgs
}

set_default_apps()
{
  xdg-mime default firefox.desktop text/html
  xdg-mime default firefox.desktop x-scheme-handler/http
  xdg-mime default firefox.desktop x-scheme-handler/https
  xdg-mime default Thunar.desktop inode/directory
}
