source "$partial_dir/env.sh"
source "$partial_dir/linux.sh"

config_pacman()
{
  timedatectl set-ntp true
  sudo pacman-mirrors -c Hong_Kong,Taiwan
}

pacman_install_pkgs()
{
  sudo pacman -Sy --needed --noconfirm `join ' ' "${pkgs[@]}"`
  unset pkgs
}

aur_install_pkgs()
{
  yay -Sy --needed `join ' ' "aur/${pkgs[@]}"`
  unset pkgs
}

prepare_arch_env()
{
  case $1 in
    'cli')
      prepare_arch_env_cli
      ;;
    'gui')
      prepare_arch_env_gui
      ;;
    'game')
      setup_arch_gaming
      ;;
    'all')
      prepare_arch_env_cli
      prepare_arch_env_gui
      ;;
    *)
      prepare_arch_env_cli
      ;;
  esac
}

prepare_arch_env_cli()
{
  pkgs=(
    android-tools
    aria2
    aws-cli
    axel
    bat
    cloc
    cmatrix
    cmus
    command-not-found
    cowsay
    cpanminus
    cpulimit
    diff-so-fancy
    docker
    docker-compose
    docker-machine
    dstat
    fasd
    fd
    figlet
    fish
    flatpak
    fortune-mod
    fzf
    gifsicle
    git
    go
    graphviz
    haproxy
    hashcat
    htop
    httpie
    hub
    imagemagick
    irssi
    jdk8-openjdk
    jdk9-openjdk
    jpegoptim
    jq
    kubectl
    lolcat
    lsd
    mc
    mediainfo
    mpc
    mpd
    mps-youtube
    mpv
    multitail
    mutt
    ncmpcpp
    neovim
    nghttp2
    nyancat
    offlineimap
    onefetch
    openssh
    p7zip
    pamixer
    pandoc
    percol
    perl-image-exiftool
    playerctl
    polipo
    prettyping
    progress
    proxychains-ng
    ranger
    ripgrep
    rsync
    shadowsocks-libev
    shellcheck
    snapd
    the_silver_searcher
    tig
    tldr
    tmux
    transmission-cli
    tree
    unrar
    unzip
    v2ray
    v2ray-domain-list-community
    v2ray-geoip
    vagrant
    vim
    w3m
    wget
    wtf
    yarn
    yay
    you-get
    zip
    zsh
  )
  pacman_install_pkgs

  # Set some configs for yay
  yay --save --nocleanmenu --nodiffmenu --noupgrademenu --noremovemake

  pkgs=(
    apache-spark
    cheat-git
    dive
    downgrader
    fpp
    fswatch
    git-lfs
    git-quick-stats
    gitflow-avh
    google-cloud-sdk
    hyperfine
    icdiff
    lf-bin
    mons
    mycli
    peco
    pgcli
    sc-im
    sparklines-git
    touchpad-state-git
    translate-shell
    ttf-weather-icons
    urlview
    wsta
    xsv
  )
  aur_install_pkgs

  install_linuxbrew
  install_nix_brew_runtimes

  env_setup
  apply_app_configs
  fix_ENOSPC

  sudo systemctl enable --now snapd.socket # enable snapd
}

prepare_arch_env_gui()
{
  pkgs=(
    android-file-transfer
    arandr
    arc-gtk-theme
    arc-icon-theme
    atom
    blueman
    chromium
    compton
    fcitx
    fcitx-configtool
    fcitx-im
    fcitx-rime
    feh
    file-roller
    firefox
    galculator
    gsimplecal
    handbrake
    hardinfo
    i3-gaps
    i3blocks
    i3status
    kdiff3
    keepassxc
    lxappearance
    lxsession
    lxtask
    maim
    moka-icon-theme
    neofetch
    network-manager-applet
    noto-fonts-emoji
    pa-applet
    polybar
    qutebrowser
    qv2ray
    redshift
    rofi
    rofi-scripts
    rxvt-unicode
    shadowsocks-qt5
    syncthing-gtk
    telegram-desktop
    termite
    thunar
    thunar-archive-plugin
    thunar-media-tags-plugin
    thunar-shares-plugin
    thunar-volman
    tilda
    ttf-font-awesome
    tumbler
    udiskie
    winetricks
    wkhtmltopdf
    wqy-zenhei
    xautomation
    xbindkeys
    xcape
    xclip
    xorg-apps
    xscreensaver
    xsel
    zathura
    zathura-cb
    zathura-djvu
    zathura-pdf-mupdf
    zathura-ps
    zeal
  )
  pacman_install_pkgs

  pkgs=(
    android-sdk
    android-sdk-platform-tools
    android-studio
    betterlockscreen
    deepin-wechat
    deepin-wine-tim
    dropbox
    etcher-bin
    feedreader
    genymotion
    git-cola
    gluqlo-git
    google-chrome-stable
    i3ass
    i3lock-color
    kitematic
    losslesscut
    mailspring
    musixmatch-bin
    nerd-fonts-complete
    notable-bin
    python-pywal
    rslsync
    screenkey
    skypeforlinux-stable-bin
    slack-desktop
    spotify
    sublime-text-dev
    sublime-merge
    ttf-ms-fonts
    typora
    urxvt-fullscreen
    urxvt-resize-font-git
    visual-studio-code-bin
    whatsapp-web-desktop
    xinit-xsession
  )
  aur_install_pkgs

  install_st
  set_default_apps
}

setup_arch_gaming()
{
  pkgs=(
    retroarch
    retroarch-assets-xmb
  )
  pacman_install_pkgs

  pkgs=(
    emulationstation
    libretro-mame-git
    retroarch-autoconfig-udev-git
  )
  aur_install_pkgs
}

set_default_apps()
{
  xdg-mime default chromium.desktop x-scheme-handler/http
  xdg-mime default chromium.desktop x-scheme-handler/https
  xdg-mime default Thunar.desktop inode/directory
}
