#!/bin/sh
# Compatibility command: the migration itself is implemented in Python.
set -eu
script_path=$0
while [ -L "$script_path" ]; do
  target=$(readlink "$script_path")
  case $target in
    /*) script_path=$target ;;
    *) script_path=$(dirname -- "$script_path")/$target ;;
  esac
done
repo_dir=$(CDPATH='' cd -- "$(dirname -- "$script_path")/../.." && pwd -P)
exec "$repo_dir/init" migrate-xdg "$@"
