#!/usr/bin/env bash

repo_path="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
partial_dir="$repo_path/bootstrap"
config_dir="$repo_path/config"
util_dir="$repo_path/util"

source "$partial_dir/util.sh"

if [ $# -lt 1 ]; then
  printUsage
fi

subroutines=()

addSubroutine()
{
  local arg=$1
  local funcCLI=$2
  local funcGUI=$3
  local funcGaming=$4

  if [[ $arg == 'game' ]]; then
    subroutines+=("$funcGaming")
  else
    if [[ $arg != 'gui' ]]; then
      subroutines+=("$funcCLI")
    fi

    if [[ $arg == 'all' || $arg == 'gui' ]]; then
      subroutines+=("$funcGUI")
    fi
  fi
}

case $1 in
  'basic')
    source "$partial_dir/env.sh"
    subroutines+=('basicSetup')
    ;;

  'ubuntu')
    source "$partial_dir/ubuntu.sh"
    addSubroutine "$2" 'prepareUbuntuEnvCLI' 'prepareUbuntuEnvGUI'
    ;;

  'arch')
    source "$partial_dir/arch.sh"
    subroutines+=('configPacman')
    addSubroutine "$2" 'prepareArchEnvCLI' 'prepareArchEnvGUI' 'setupArchGaming'
    ;;

  'macos' | 'osx')
    source "$partial_dir/macos.sh"
    addSubroutine "$2" 'prepareMacOSEnvCLI' 'prepareMacOSEnvGUI' 'setupMacOSGaming'
    ;;

  'chromeos')
    source "$partial_dir/chromeos.sh"
    subroutines+=('prepareChromeOS')
    ;;

  'cygwin')
    source "$partial_dir/cygwin.sh"
    subroutines+=('checkAdmin')
    subroutines+=('setupCygwinEnv')
    subroutines+=('installSage')
    subroutines+=('installCygwinPackages')
    ;;

  'npmg')
    source "$partial_dir/pkg.sh"
    subroutines+=('installNpmPackages')
    ;;

  'zgen')
    source "$partial_dir/shell.sh"
    subroutines+=('zgenSetup')
    ;;

  'zplug')
    source "$partial_dir/shell.sh"
    subroutines+=('zplugSetup')
    ;;

  'run')
    echo "Run '$3' in '$partial_dir/$2.sh'..."
    echo
    source "$partial_dir/$2.sh"
    subroutines+=("$3")
    ;;

  *)
    printUsage
    ;;
esac

# Run the pushed subroutines one by one
for i in "${subroutines[@]}"; do
  eval "$i"
done

echo 'All jobs done. Have a nice day...'
exit 0
