#!/bin/bash

repo_path="$(dirname "$0")"
partial_dir="$repo_path/bootstrap"
config_dir="$(pwd)/$repo_path/config"

source "$partial_dir/util.sh"

if [ $# -lt 1 ]; then
  printUsage
fi

subroutines=()

case $1 in
  'ubuntu' | 'wsl')
    source "$partial_dir/ubuntu.sh"

    if [[ $1 == 'wsl' || $2 != 'gui' ]]; then
      subroutines+=('prepareUbuntuEnvCLI')
    fi

    if [[ $1 != 'wsl' && ($2 == 'all' || $2 == 'gui') ]]; then
      subroutines+=('prepareUbuntuEnvGUI')
    fi
    ;;

  'arch' | 'alwsl')
    source "$partial_dir/arch.sh"

    if [[ $1 == 'alwsl' || $2 != 'gui' ]]; then
      subroutines+=('prepareArchEnvCLI')
    fi

    if [[ $1 != 'alwsl' && ($2 == 'all' || $2 == 'gui') ]]; then
      subroutines+=('prepareArchEnvGUI')
    fi
    ;;

  'macos' | 'osx')
    source "$partial_dir/macos.sh"

    if [[ $2 != 'gui' ]]; then
      subroutines+=('prepareMacOSEnvCLI')
    fi

    if [[ $2 == 'all' || $2 == 'gui' ]]; then
      subroutines+=('prepareMacOSEnvGUI')
    fi
    ;;

  *)
    printUsage
    ;;
esac

# Run the pushed subroutines one by one
for i in "${subroutines[@]}"; do
  eval "$i"
done

echo 'All jobs done. Have a nice day...'
exit 0
