#!/bin/sh

exists()
{
  command -v "$1" >/dev/null 2>&1
}

xrandr \
  --output LVDS1 --auto \
  --output DP1 --off \
  --output HDMI1 --auto --primary --right-of LVDS1 \
  --output VGA1 --off \
  --output VIRTUAL1 --off

exists wallpaper && wallpaper
exists i3-msg && i3-msg restart
