#!/usr/bin/env python3
"""Generate native binding tables. No desktop is reloaded by this command."""
import argparse
import json
from pathlib import Path
import re
from localize import catalog

ROOT = Path(__file__).resolve().parents[2]
SOURCE = Path(__file__).with_name('keys.json')


def bindings(data):
    result = list(data['bindings'])
    for role, spec in data['roles'].items():
        if spec.get('key'):
            result.append(dict(key=spec['key'], action='app.' + role))
    seen = set()
    for item in result:
        chord = (item['key'], item.get('shift', False))
        if chord in seen:
            raise ValueError(f'Duplicate Hyper binding: {chord}')
        seen.add(chord)
    for role, spec in data['roles'].items():
        for app in spec['apps']:
            if app not in data['apps']:
                raise ValueError(f'Unknown app {app} in {role}')
    for name, adaptive in data['adaptiveLayouts'].items():
        if name not in data['layouts'] or adaptive is not True:
            raise ValueError(f'Invalid adaptive layout: {name}')
    for name, cycle in data['layoutCycles'].items():
        if len(cycle)<2 or len(set(cycle))!=len(cycle) or any(layout not in data['layouts'] for layout in cycle):
            raise ValueError(f'Invalid layout cycle: {name}')
    return result


def lua(value):
    if isinstance(value, dict):
        return '{' + ','.join('[' + lua(k) + ']=' + lua(v) for k, v in value.items()) + '}'
    if isinstance(value, list):
        return '{' + ','.join(map(lua, value)) + '}'
    return json.dumps(value, ensure_ascii=False)


def ahk(value):
    if isinstance(value, dict):
        return '{' + ', '.join(ahk(k) + ': ' + ahk(v) for k, v in value.items()) + '}'
    if isinstance(value, list):
        return '[' + ', '.join(map(ahk, value)) + ']'
    if isinstance(value, bool):
        return 'true' if value else 'false'
    if isinstance(value, str):
        return '"' + value.replace('`', '``').replace('"', '""') + '"'
    return str(value)


XKEY = {'return':'Return', 'delete':'BackSpace', 'escape':'Escape', 'tab':'Tab',
        'left':'Left', 'right':'Right', 'up':'Up', 'down':'Down',
        'home':'Home', 'end':'End', 'pageup':'Prior', 'pagedown':'Next',
        '[':'bracketleft', ']':'bracketright',
        ';':'semicolon', "'":'apostrophe', '=':'equal', '/':'slash', ',':'comma', '`':'grave'}


def outputs(data):
    data = dict(data, bindings=bindings(data))
    data['i18n'] = catalog(data)
    result = {}
    result['config/hammerspoon/private/modules/hyper-generated.lua'] = '-- Generated by config/hyper/generate.py\nreturn ' + lua(data) + '\n'
    assignments = ['  data := {}']
    def assign(target, value):
        # AHK v1 has expression-size/token limits, even below its line limit.
        if isinstance(value, dict):
            assignments.append('  ' + target + ' := {}')
            for key, item in value.items():
                assign(target + '[' + ahk(key) + ']', item)
        elif isinstance(value, list):
            assignments.append('  ' + target + ' := []')
            for index, item in enumerate(value, 1):
                assign(target + '[' + str(index) + ']', item)
        else:
            assignments.append('  ' + target + ' := ' + ahk(value))
    for key, value in data.items():
        if key != 'i18n':
            assign('data[' + ahk(key) + ']', value)
    assignments.append('  data.i18n := {en: {}, zh: {}}')
    for lang,labels in data['i18n'].items():
        assignments += [f'  data.i18n.{lang}[{ahk(key)}] := {ahk(value)}' for key,value in labels.items()]
    # AHK v1 otherwise decodes UTF-8 as the Windows ANSI code page, which can
    # consume closing quotes after Chinese text and prevent startup entirely.
    result['config/autohotkey/lib/hyper-generated.ahk'] = '\ufeff; Generated by config/hyper/generate.py\nhyperConfig() {\n' + '\n'.join(assignments) + '\n  return data\n}\n'
    i3, xb = [], []
    for b in data['bindings']:
        key = XKEY.get(b['key'], b['key'])
        shift = 'Shift+' if b.get('shift') else ''
        # Input actions execute on key-down for auto-repeat. The backend strips
        # physical modifiers before injecting the intended editing chord.
        release = '' if b['action'].startswith(('edit.', 'select.', 'mouse.')) else '--release '
        command = 'hyper ' + b['action']
        if b['action'].startswith(('edit.', 'select.')):
            kind, direction = b['action'].split('.')
            target = {'left':'Left','right':'Right','up':'Up','down':'Down','home':'Home','end':'End','pageup':'Prior','pagedown':'Next'}[direction]
            command = 'xdotool key --clearmodifiers ' + ('shift+' if kind == 'select' else '') + target
        elif b['action'].startswith('mouse.'):
            dx, dy = {'left':(-10,0),'right':(10,0),'up':(0,-10),'down':(0,10)}[b['action'].split('.')[1]]
            command = f'xdotool mousemove_relative -- {dx} {dy}'
        i3.append(f'bindsym {release}Mod3+{shift}{key} exec --no-startup-id {command}')
        suffix = '' if not release else ' + Release'
        xb.append(f'"{command}"\n  {shift}Mod3 + {key}{suffix}')
    result['config/hyper/i3.conf'] = '# Generated by config/hyper/generate.py\n' + '\n'.join(i3) + '\n'
    old_i3 = (ROOT / 'config/i3/config').read_text()
    old_i3 = re.sub(r'# BEGIN GENERATED HYPER\n.*?# END GENERATED HYPER\n?', '', old_i3, flags=re.S)
    old_i3 = re.sub(r'^bindsym .*\$hyper[^\n]*\n', '', old_i3, flags=re.M)
    old_i3 = re.sub(r'^# >> (?:Hyper shortcuts|Hyper\+Shift shortcuts|Vim cursor move: Hyper \+ hjkl)\n\s*(?=#)', '', old_i3, flags=re.M)
    old_i3 = old_i3.replace('include ~/.config/hyper/i3.conf\n', '')
    old_i3 = old_i3.replace('# Shared Hyper bindings\n', '')
    # i3 4.16 (Debian stable on existing devboxes) predates config includes.
    result['config/i3/config'] = old_i3.rstrip() + '\n\n# BEGIN GENERATED HYPER\n' + '\n'.join(i3) + '\n# END GENERATED HYPER\n'
    old_x = (ROOT / 'config/x/.xbindkeysrc').read_text().split('# BEGIN GENERATED HYPER')[0]
    old_x = re.sub(r'^"[^\n]*"\n[ \t]*[^\n]*Mod3[^\n]*\n', '', old_x, flags=re.M)
    old_x = re.sub(r'^# >> (?:Hyper shortcuts|Hyper\+Shift shortcuts|Vim cursor move: Hyper \+ hjkl)\n\s*(?=#)', '', old_x, flags=re.M)
    result['config/x/.xbindkeysrc'] = old_x.rstrip() + '\n\n# BEGIN GENERATED HYPER\n' + '\n\n'.join(xb) + '\n# END GENERATED HYPER\n'
    lines = ['# Hyper shortcuts', '', 'Generated from `keys.json`. H = hold Caps Lock; tap = Esc.', '', '| Chord | Action |', '| --- | --- |']
    for b in data['bindings']:
        lines.append('| H+' + ('Shift+' if b.get('shift') else '') + b['key'] + ' | ' + b['action'] + ' |')
    result['config/hyper/KEYS.md'] = '\n'.join(lines) + '\n'
    rectangle_path = ROOT / 'config/RectangleApp/RectangleConfig.json'
    rectangle = json.loads(rectangle_path.read_text())
    # Hammerspoon is now the sole owner of Hyper window shortcuts and undo.
    rectangle['shortcuts'] = {name: spec for name, spec in rectangle['shortcuts'].items()
                              if spec.get('modifierFlags') not in (1835008, 1966080)}
    result['config/RectangleApp/RectangleConfig.json'] = json.dumps(rectangle, indent=2) + '\n'
    return result


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    stale = []
    for name, content in outputs(json.loads(SOURCE.read_text())).items():
        path = ROOT / name
        if not path.exists() or path.read_text() != content:
            stale.append(name)
            if not args.check:
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(content)
    if args.check and stale:
        raise SystemExit('Stale generated files: ' + ', '.join(stale))
    print(('Checked' if args.check else 'Generated') + ' Hyper bindings')


if __name__ == '__main__':
    main()
