add_newline = true
palette = "default"

format = "$os$directory$git_branch$git_status$fill$status$cmd_duration$jobs$python$time$line_break$character"

[os]
disabled = false
format = "[$symbol]($style) "
style = "white"

[directory]
format = "[$path]($style) "
style = "bold color_turquoise"
truncation_length = 0
truncate_to_repo = false

[git_branch]
format = "[$symbol$branch]($style)"
symbol = " "
style = "color_green"

[git_status]
format = "[$all_status$ahead_behind]($style) "
style = "color_yellow"
conflicted = "~${count} "
ahead = "⇡${count} "
behind = "⇣${count} "
diverged = "⇕⇡${ahead_count}⇣${behind_count} "
untracked = "?${count} "
stashed = "*${count} "
modified = "!${count} "
staged = "+${count} "
renamed = "»${count} "
deleted = "✘${count} "

[fill]
symbol = " "

[status]
disabled = false
format = "[$symbol$status]($style) "
symbol = "✘"
style = "color_red"

[cmd_duration]
min_time = 3_000
format = "[$duration]($style) "
style = "color_muted"

[jobs]
format = "[$symbol$number]($style) "
symbol = "✦"
style = "color_green"

[python]
format = "[$virtualenv]($style) "
style = "color_turquoise"

[time]
disabled = false
format = "[$time]($style)"
time_format = "%H:%M:%S"
style = "color_muted"

[character]
success_symbol = "[❯](color_green)"
error_symbol = "[❯](color_red)"
vimcmd_symbol = "[❮](color_green)"
vimcmd_visual_symbol = "[V](color_green)"
vimcmd_replace_one_symbol = "[▶](color_green)"

[palettes.default]
color_turquoise = "31"
color_green = "76"
color_yellow = "178"
color_red = "196"
color_muted = "101"
