-- Only policy metadata is read here, never Alfred's clipboard database.
local M={}
local protected={
  'Keychain Access','SecurityAgent','1Password','1Password 7','1Password 8',
  'Wallet','LastPass','MacPass','Passwords','Bitwarden','KeePassXC','KeePassX',
  'KeePass','Strongbox','Enpass','Dashlane','Proton Pass','NordPass',
  'com.apple.keychainaccess','com.apple.SecurityAgent','com.apple.Passwords',
  'com.agilebits.onepassword7','com.1password.1password','com.bitwarden.desktop',
  'org.keepassxc.keepassxc','com.hicknhacksoftware.MacPass',
}
local sensitive={['org.nspasteboard.ConcealedType']=true,
  ['org.nspasteboard.TransientType']=true,['org.nspasteboard.AutoGeneratedType']=true,
  ['com.agilebits.onepassword']=true}
local function read(path)
  local ok,value=pcall(hs.plist.read,path)
  return ok and type(value)=='table' and value or {}
end
function M.new()
  local self={excluded={}}
  function self:rebuild()
    local excluded={}
    for _,list in ipairs({protected,self.alfredNames or {},hs.settings.get('hyper.clipboardExcludedApps') or {}}) do
      for _,name in ipairs(list) do if type(name)=='string' then excluded[name:lower()]=true end end
    end
    self.excluded=excluded
  end
  function self:sync()
    local home=os.getenv('HOME')
    local config=os.getenv('XDG_CONFIG_HOME') or home..'/.config'
    local prefs=read(home..'/Library/Preferences/com.runningwithcrayons.Alfred-Preferences.plist')
    local sync=prefs.syncfolder
    if type(sync)=='string' then sync=sync:gsub('^~',function()return home end) end
    local paths={}
    if sync and sync~='' then paths[#paths+1]=sync..'/Alfred.alfredpreferences/preferences/features/clipboard/prefs.plist' end
    paths[#paths+1]=config..'/dotfiles/config/AlfredApp/Alfred.alfredpreferences/preferences/features/clipboard/prefs.plist'
    paths[#paths+1]=home..'/Library/Application Support/Alfred/Alfred.alfredpreferences/preferences/features/clipboard/prefs.plist'
    for _,path in ipairs(paths) do
      local blacklist=read(path).blacklist
      if type(blacklist)=='table' then
        local saved=hs.settings.set('hyper.clipboardAlfredBlacklist',{names=blacklist,source=path})
        if saved==false then return false end
        self.alfredNames=blacklist;self.source=path;self:rebuild();return true
      end
    end
    return false -- Missing/unreadable preferences must not erase the snapshot.
  end
  function self:blocked(app,types)
    if not app then return true end -- Unknown origin: fail closed.
    if self.excluded[(app:name() or ''):lower()] or self.excluded[(app:bundleID() or ''):lower()] then return true end
    for _,uti in ipairs(types or {}) do if sensitive[uti] then return true end end
    return false
  end
  local snapshot=hs.settings.get('hyper.clipboardAlfredBlacklist')
  if type(snapshot)=='table' and type(snapshot.names)=='table' then
    self.alfredNames=snapshot.names;self.source=snapshot.source
  else self:sync() end
  self:rebuild()
  return self
end
return M
