#!/usr/bin/env sh

set -e

if [ -z "$1" ]; then
  echo "Usage: git-clone-bare <git-url> [directory]" >&2
  exit 1
fi

REPO_URL="$1"
DIR="${2:-$(basename "$REPO_URL" .git)}"

mkdir -p "$DIR"
cd "$DIR"

git clone --bare "$REPO_URL" .git

git config remote.origin.fetch '+refs/heads/*:refs/remotes/origin/*'

git fetch

git for-each-ref --format='%(refname:short)' refs/heads | \
  xargs -n1 -I{} git branch --set-upstream-to=origin/{}

printf "Bare clone ready in %s\n" "$DIR"