#!/usr/bin/env bash

print_usage()
{
  cat << 'EOB' >&2
killbp - Kill the process that occupies a certain port

[Synopsis]

  killbp [port_number]

[Examples]

  killbp 3001
EOB
  exit 0
}

main()
{
  if [ $# = 0 ]; then
    print_usage
  fi

  kill $(lsof -nP -i4TCP:"$1" | grep LISTEN | awk '{ print $2 }')
}

main "$@"
