#!/usr/bin/env bash

print_usage()
{
  cat << 'EOB' >&2
mann - Locate the position of an option in command's man page

[Synopsis]

  mann [command] [option]

[Example]

  mann wget -O
EOB
  exit 0
}

main()
{
  if [ $# = 0 ]; then
    print_usage
  elif [ $# = 1 ]; then
    man "$1"
  else
    man "$1" | less -p "^( |\\t){0,8}$2 "
  fi
}

main "$@"
