#!/usr/bin/env bash

print_usage()
{
  echo "Locate the position of an option in command's man page."
  echo 'Usage:'
  echo '  mann [command] [option]'
  echo 'Example:'
  echo '  mann wget -O'
  exit 1
}

main()
{
  if [ $# -lt 1 ]; then
    print_usage
  elif [ $# -eq 1 ]; then
    man "$1"
  else
    man "$1" | less -p "^( |\\t){0,8}$2 "
  fi
}

main "$@"
