#!/bin/bash

if [ -f ~/.agent-profile ]; then
  source ~/.agent-profile
  return
fi

# Create per-user instance of ssh-agent
ps -u $(whoami) | grep '[ ]ssh-agent' &> /dev/null
if [ $? -ne 0 ]; then
  eval $(ssh-agent)
fi

# Add all private keys start with 'id_'
ssh-add $(find ~/.ssh -name 'id_*' ! -name '*.*' | tr '\n' ' ')

echo "export SSH_AGENT_PID=$SSH_AGENT_PID" > ~/.agent-profile
echo "export SSH_AUTH_SOCK=$SSH_AUTH_SOCK" >> ~/.agent-profile

if [ "$ZSH_VERSION" ]; then
  zshexit() { ssh-agent -k; \rm ~/.agent-profile; exit }
else
  trap 'ssh-agent -k; \rm ~/.agent-profile; exit' EXIT
fi
