#!/usr/bin/env bash

# Terminate already running bar instances
killall -q polybar

# Wait until the processes have been shut down
while pgrep -x polybar >/dev/null; do sleep 1; done

if pgrep -x i3 >/dev/null; then
  # Set I3SOCK for polybar's i3 module to connect
  export I3SOCK=$(i3 --get-socketpath)

  for i in $(polybar --list-monitors | awk -F: '{print $1}'); do
    MONITOR=$i polybar -c ~/.config/polybar/config.ini i3 &
  done
  echo 'Bars launched...'
else
  echo 'Bars not launched since i3 is not running.'
fi
