#!/bin/bash

# Terminate already running bar instances
killall -q polybar

# Wait until the processes have been shut down
while pgrep -x polybar >/dev/null; do sleep 1; done

for i in $(polybar -m | awk -F: '{print $1}'); do
  MONITOR=$i polybar i3 -c ~/.config/polybar/config &
done

echo "Bars launched..."
